export {
  CONTENT_TYPES,
  listContentTypes,
  listContentTypesByPhase,
  resolveContentType,
  type ContentTypeKey,
  type ContentTypeSpec,
  type FieldSpec,
  type FieldKind,
  type CmsRegistryPhase,
} from "@/lib/cms/content-types";
export type {
  ContentDocument,
  ContentFieldValue,
  PublishedAboutLocalTrust,
  PublishedAboutStat,
  PublishedAudience,
  PublishedCompanyValue,
  PublishedContactInfo,
  PublishedDeckMaterial,
  PublishedExperienceStep,
  PublishedFaq,
  PublishedFenceMaterial,
  PublishedFenceType,
  PublishedFencingOptionNav,
  PublishedFooterLink,
  PublishedHeroCopy,
  PublishedLegalLink,
  PublishedMaterialComparison,
  PublishedMaterialFaq,
  PublishedMaterialGuidance,
  PublishedNavLink,
  PublishedNeed,
  PublishedProcessStep,
  PublishedProject,
  PublishedService,
  PublishedServiceTown,
  PublishedTestimonial,
  PublishedTrustPoint,
} from "@/lib/cms/types";
export {
  listContent,
  getContent,
  updateContent,
  contentCounts,
} from "@/lib/cms/memory-store";

export {
  CMS_PUBLIC_ROADMAP,
  shippedContentKeys,
  upcomingContentTypes,
  cutoverContentTypes,
  type CmsPhase,
  type PlannedContentType,
} from "@/lib/cms/roadmap";

export {
  getPublishedFaqs,
  faqsSourceIsCms,
  getPublishedTestimonials,
  testimonialsSourceIsCms,
  getPublishedProjects,
  projectsSourceIsCms,
  getPublishedFenceTypes,
  fenceTypesSourceIsCms,
  getPublishedServices,
  servicesSourceIsCms,
  getPublishedAboutLocalTrust,
  getPublishedAboutStats,
  getPublishedCompanyValues,
  aboutSourceIsCms,
  getPublishedServiceTowns,
  serviceAreaSourceIsCms,
  getPublishedFenceMaterials,
  getPublishedDeckMaterials,
  getPublishedMaterialGuidance,
  getPublishedMaterialComparison,
  materialsSourceIsCms,
  getPublishedProcessTimeline,
  processTimelineSourceIsCms,
  getPublishedHeroCopy,
  heroCopySourceIsCms,
  getPublishedTrustPoints,
  trustPointsSourceIsCms,
  getPublishedYourNeeds,
  yourNeedsSourceIsCms,
  getPublishedKabaExperience,
  kabaExperienceSourceIsCms,
  getPublishedNavLinks,
  navLinksSourceIsCms,
  getPublishedFooterLinks,
  footerLinksSourceIsCms,
  getPublishedContactInfo,
  contactInfoSourceIsCms,
  getPublishedFencingOptionsNav,
  fencingOptionsNavSourceIsCms,
  getPublishedLegalLinks,
  legalLinksSourceIsCms,
  getPublishedMaterialFaqs,
  materialFaqsSourceIsCms,
  siteCopyHomeSourceIsCms,
} from "@/lib/cms/public";
